"""initial migration

Revision ID: a504b54eb04f
Revises: 
Create Date: 2025-06-01 05:02:52.816348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a504b54eb04f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipients',
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('recipient_id', name=op.f('pk_recipients'))
    )
    op.create_index(op.f('ix_recipients_recipient_email'), 'recipients', ['recipient_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipients_recipient_email'), table_name='recipients')
    op.drop_table('recipients')
    # ### end Alembic commands ###
