name: RMQ-Notifications CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use dev .dockerignore for CI build
        run: cp .dockerignore.dev .dockerignore

      - name: Build Docker image
        run: docker build -t rmq-notifications -f ./deploy/prod/dev.Dockerfile .

      - name: Create .env file from secrets
        run: |
          echo "${{ secrets.DEPLOY }}" > .env
          sed -i 's/\r$//' .env
          echo "Generated .env file content:"
          head -n 3 .env

      - name: Run lint with environment
        run: |
          docker run --rm \
            --env-file .env \
            -w /app \
            rmq-notifications \
            ruff check .
        
      - name: Run mypy static type checking
        run: |
          docker run --rm \
            --env-file .env \
            -w /app/ \
            rmq-notifications \
            mypy .

      - name: Run tests with environment
        run: |
          docker run --rm \
            --env-file .env \
            -w /app \
            rmq-notifications \
            python -m pytest

      - name: Cleanup
        run: rm -f .env 
        if: always()